workflows:
  flutter-integration-tests:
    name: Flutter Integration Tests
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    environment:
      flutter: stable
    scripts:
      - name: Run iOS Integration Tests
        script: |
          make emulator_ios_create
          make ios_test

      - name: Run Android Integration Tests
        script: |
          export ADB_BINARY_PATH=/usr/local/share/android-sdk
          make emulator_android_create
          make android_test
