workflows:
  flutter-integration-tests-ios:
    name: Flutter Integration Tests
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    environment:
      flutter: stable
    scripts:
      - name: Run iOS Integration Tests
        script: |
          cd integration_test_app
          flutter emulators --launch ios
          flutter test integration_test/icu_tokenizer_test.dart
