name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y lcov libicu-dev

      - name: Install addlicense
        run: go install github.com/google/addlicense@latest

      - run: make cicd
